# Generated by Django 6.0.6 on 2026-06-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('eligibility_criteria', models.DecimalField(decimal_places=2, max_digits=4)),
                ('package', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
